In [ ]:
import numpy
err1 = [0.01450184 0.01737251 0.02294599 0.02983828 0.03779991 0.04703996
 0.05727503 0.06829932 0.08007097 0.09247988 0.10538001 0.11865263
 0.13196798 0.14556459 0.15925826 0.17336114 0.18762241 0.20182852
 0.21586122 0.23011686 0.24438167]

idx1 = [ 80  84  88  92  96 100 104 108 112 116 120 124 128 132 136 140 144 148
  152 156 160]
  
idx2 =  [80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114
  116 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150
  152 154 156 158 160]

err2 = [0.01450184 0.0235571  0.0401405  0.05800507 0.07612654 0.09423007
 0.11220076 0.12997518 0.14750959 0.16477056 0.18173231 0.1983744
 0.21467969 0.23063429 0.2462263  0.26144582 0.27628475 0.29073644
 0.3047959  0.31845996 0.33172652 0.34459448 0.35706452 0.36913893
 0.3808207  0.3921135  0.4030218  0.41355103 0.42370728 0.4334977
 0.44293007 0.45201266 0.46075463 0.4691653  0.47725454 0.48503292
 0.49251112 0.4997005  0.5066128  0.51326025 0.5196549 ]